


export const REQUESTING_POSTS = 'USER.REQUESTING_POSTS'
export const FAILED_REQUESTING_POSTS = 'USER.FAILED_REQUESTING_POSTS'
export const SET_POSTS = 'USER.SET_POSTS'

export const REQUESTING_POST = 'USER.REQUESTING_POST'
export const FAILED_REQUESTING_POST = 'USER.FAILED_REQUESTING_POST'
export const SET_POST = 'USER.SET_POST'

export const CLEAR_POSTS = 'USER.CLEAR_POSTS'