


export const REQUESTING_USER = 'USER.REQUESTING_USER'
export const FAILED_REQUESTING_USER = 'USER.FAILED_REQUESTING_USER'
export const FAILED_REGISTER_REQUEST = 'USER.FAILED_REQUEST'
export const SET_USER = 'USER.SET_USER'
export const FAILED_LOGIN_REQUEST = 'USER.FAILED_REQUEST'
export const REGISTER_USER = 'USER.REGISTER_USER'
export const SET_GOOGLE_USER = 'USER.SET_GOOGLE_USER'


export const FOLLOW_USER = 'USER.FOLLOW_USER'
export const CLEAR_USER = 'USER.CLEAR_USER'